hook.Add("PostGamemodeLoaded", "Bloodshed:LoadAdminPermissions", function()
    CAMI.RegisterPrivilege("mur_give")
    CAMI.RegisterPrivilege("mur_restartround")
    CAMI.RegisterPrivilege("mur_resetguilt")
    CAMI.RegisterPrivilege("mur_nextgamemode")
    CAMI.RegisterPrivilege("mur_nexttraitor")
    CAMI.RegisterPrivilege("mur_forcespawn")
    CAMI.RegisterPrivilege("mur_resetguilt_ply")
    CAMI.RegisterPrivilege("mur_explode")
    CAMI.RegisterPrivilege("mur_grenadethrow")
    CAMI.RegisterPrivilege("mur_bomj")
end )